---
  - name: chang owner for app
    become: yes
    shell: bash -lc "sudo chown -R ubuntu:ubuntu /home/ubuntu/raisetech-app"

  - name: chang owner for nginx
    become: yes
    shell: bash -lc "sudo chown -R ubuntu:ubuntu /etc/nginx"

  - name: Stop unicorn
    become: no
    shell: bash -lc "rails unicorn:stop"
    args:
      chdir: /home/ubuntu/raisetech-app
    changed_when: False
    ignore_errors: True

  - name: Start unicorn
    become: no
    shell: bash -lc "rails unicorn:start"
    args:
      chdir: /home/ubuntu/raisetech-app

  - name: restart nginx
    service:
      name: nginx
      state: restarted

